[package]
name = "Onnyx"
authors = ["Levy-Y <65444028+Levy-Y@users.noreply.github.com>"]
version = "0.1.0"
edition = "2024"
categories = ["embedded", "hardware-support"]
keywords = ["embedded", "svc", "idf", "esp-idf", "esp32-s3"]
description = "A reimagined USB Rubber Ducky firmware written in rust for the esp32-s3"
repository = "https://github.com/Levy-Y/onnyx"
license = "GNU AGPLv3"
readme = "README.md"

[[bin]]
name = "Onnyx"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"

[features]
default = []

experimental = ["esp-idf-svc/experimental"]


[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.51", features = ["experimental", "std"] }
esp-idf-hal = { version = "0.45", features = ["experimental"] }
esp-idf-sys = { version = "0.36.1", features = ["binstart"] }

embedded-graphics = "0.8.1"
kolibri-embedded-gui = "0.1.0"
anyhow = "1.0.100"
apa102-spi = "0.5"
smart-leds = "0.4"
usb-device = "0.3.2"
st7735-lcd = "0.10.0"
serde = { version = "1.0.227", features = ["derive", "serde_derive"] }
serde_json = "1.0.149"
libc = "0.2.180"
strum = "0.28.0"
strum_macros = "0.28.0"

[build-dependencies]
embuild = "0.33"

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/mdns", version = "1.2" }
[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/tinyusb", version = "^0.15.0~2" }
[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp_tinyusb", version = "^1.3.1" }
